networks:
  system_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.77.0.0/16

services:
  app:
    build:
      context: ./src
    # restart: on-failure
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/w2w_python?authSource=admin
    networks:
      system_network:
    container_name: app

  mongodb:
    image: mongo:7.0
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    container_name: mongodb
    networks:
      system_network:

volumes:
  mongodata:


